apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cs3x2jk1f-nodejs
  janus-idp.io/tekton: cs3x2jk1f-nodejs
  backstage.io/kubernetes-id: cs3x2jk1f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cs3x2jk1f-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
