apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cs3x2jk1f-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cs3x2jk1f-nodejs 
  name: cs3x2jk1f-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cs3x2jk1f-nodejs 
